### PR TITLE
#68 Fix the Test Suite

### LINKED ISSUE #68: Fix the Test suite
# Description
I broke the test suite when I merged #67. I didn't have regression tests running, and I thought I did.

# Changes
The handle should be a FactoryBot sequence, so we don't have duplicate profiles.
Let's add numbers to the handle as well to make cafce25 happy, and support these sequences.

### PR DESCRIPTION
**Pull request by yagosansz**
Hi @ChaelCodes,

I also had to change `spec/requests/profiles_spec.rb:141`, because updating the handle to be a FactoryBot sequence ended up breaking that line - the `handle` would always be "ChaelCodes".

This time I ran `docker-compose run --rm web bundle exec rspec` to be sure my changes didn't add any bugs =)

Looking forward for your review =)

Closes #68

### CODE REVIEW

File: app/models/profile.rb [hunk 1]
```diff
@@ -13,7 +13,7 @@ class Profile < ApplicationRecord
   # Whether they are "buddy" or "friend"
   has_many :buddyships, class_name: "Friendship", foreign_key: "buddy_id", dependent: :destroy, inverse_of: :buddy
   has_many :friendships, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy, inverse_of: :friend
-  validates :handle, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "Only letters are allowed" }, uniqueness: { case_sensitive: true }
+  validates :handle, presence: true, format: { with: /\A[a-zA-Z]+[0-9]*\z/, message: "Only letters and numbers are allowed" }, uniqueness: { case_sensitive: true }
```
Comment (ChaelCodes) [inline app/models/profile.rb:16]: Can we instead use `[a-zA-z0-9]` so our users can put numbers wherever?

**Review by ChaelCodes — COMMENTED** [review]
Ah, can we add numbers anywhere in the Regex? Then this is good to go!

**Comment by ChaelCodes** [comment]
Oh, would you run robocop as well? I'm almost off work and then I should be able to fix the CI builds on forked repos.

**Comment by ChaelCodes** [comment]
Would you mind rebasing with the changes? I think I've fixed the CI tooling.

File: app/models/profile.rb [hunk 2]
```diff
@@ -13,7 +13,7 @@ class Profile < ApplicationRecord
   # Whether they are "buddy" or "friend"
   has_many :buddyships, class_name: "Friendship", foreign_key: "buddy_id", dependent: :destroy, inverse_of: :buddy
   has_many :friendships, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy, inverse_of: :friend
-  validates :handle, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "Only letters are allowed" }, uniqueness: { case_sensitive: true }
+  validates :handle, presence: true, format: { with: /\A[a-zA-Z0-9]+\z/, message: "Only letters and numbers are allowed" }, uniqueness: { case_sensitive: true }
```
Comment (ChaelCodes) [inline app/models/profile.rb:16]:
```suggestion
  # rubocop:disable Rails/UniqueValidationWithoutIndex, 
  validates :handle, presence: true, format: { with: /\A[a-zA-Z0-9]+\z/, message: "Only letters and numbers are allowed" }, uniqueness: { case_sensitive: true }
  # rubocop:disable Rails/UniqueValidationWithoutIndex, 
```

**Review by ChaelCodes — APPROVED** [review]
I'm still seeing the build broken in CI, but I'm going to try merging anyway and see if it fixes things.
